FROM node:22-alpine

WORKDIR /app

COPY . /app

ENV DATABASE_URL=${DATABASE_URL}
ENV PAYLOAD_SECRET=${PAYLOAD_SECRET}
ENV PAYLOAD_ADMIN_EMAIL=${PAYLOAD_ADMIN_EMAIL}
ENV PAYLOAD_ADMIN_PASSWORD=${PAYLOAD_ADMIN_PASSWORD}

RUN echo "*** debugging"
RUN echo ${PAYLOAD_ADMIN_EMAIL}}

RUN npm install
RUN npm run build

CMD HOSTNAME="0.0.0.0" npm start