FROM node:22-alpine

WORKDIR /app

COPY . /app

ARG DATABASE_URL
ARG PAYLOAD_SECRET
ARG PAYLOAD_ADMIN_EMAIL
ARG PAYLOAD_ADMIN_PASSWORD

RUN echo "*** debugging"
RUN echo ${PAYLOAD_ADMIN_EMAIL}

RUN npm install
RUN npm run build

CMD HOSTNAME="0.0.0.0" npm start